version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - ecommerce

  user-service:
    image: garapatimanoj/user-service
    container_name: user-service
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - MONGODB_URI=mongodb://mongo:27017/ecommerce_users
      - JWT_SECRET=your-jwt-secret-key
    depends_on:
      - mongo
    networks:
      - ecommerce

  product-service:
    image: garapatimanoj/product-service
    container_name: product-service
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
      - MONGODB_URI=mongodb://mongo:27017/ecommerce_products
    depends_on:
      - mongo
    networks:
      - ecommerce

  cart-service:
    image: garapatimanoj/cart-service
    container_name: cart-service
    ports:
      - "3003:3003"
    environment:
      - PORT=3003
      - PRODUCT_SERVICE_URL=http://product-service:3002
    depends_on:
      - product-service
    networks:
      - ecommerce

  order-service:
    image: garapatimanoj/order-service
    container_name: order-service
    ports:
      - "3004:3004"
    environment:
      - PORT=3004
      - USER_SERVICE_URL=http://user-service:3001
      - CART_SERVICE_URL=http://cart-service:3003
      - PRODUCT_SERVICE_URL=http://product-service:3002
    depends_on:
      - user-service
      - cart-service
      - product-service
    networks:
      - ecommerce

  frontend:
    image: garapatimanoj/frontend
    container_name: frontend
    ports:
      - "3000:80"
    environment:
      - REACT_APP_USER_SERVICE_URL=http://user-service:3001
      - REACT_APP_PRODUCT_SERVICE_URL=http://product-service:3002
      - REACT_APP_CART_SERVICE_URL=http://cart-service:3003
      - REACT_APP_ORDER_SERVICE_URL=http://order-service:3004
    depends_on:
      - user-service
      - product-service
      - cart-service
      - order-service
    networks:
      - ecommerce

volumes:
  mongo-data:

networks:
  ecommerce:
    driver: bridge