apiVersion: v1
kind: ConfigMap
metadata:
  name: order-service-config
data:
  PORT: "3004"
  USER_SERVICE_URL: "http://user-service:3001"
  CART_SERVICE_URL: "http://cart-service:3003"
  PRODUCT_SERVICE_URL: "http://product-service:3002"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: garapatimanoj/order-service
          ports:
            - containerPort: 3004
          envFrom:
            - configMapRef:
                name: order-service-config
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  selector:
    app: order-service
  ports:
    - port: 3004
      targetPort: 3004
